### ISSUE TITLE
Agent Smith Breaking Code Cleanup

### ISSUE THREAD

**Issue by Rob300** [sheitmann/AgentSmith#16]
Code Cleanup no longer works whens Agent Smith is installed, This is show in the Jet Brains Log file shown below

--- EXCEPTION #1/2 [ArgumentOutOfRangeException]
Message = “Specified argument was out of the range of valid values.”
ExceptionPath = Root.InnerException
ClassName = System.ArgumentOutOfRangeException
HResult = COR_E_ARGUMENTOUTOFRANGE=80131502
Source = ReSharper.AgentSmith
ParamName = profileType
StackTraceString = “
  at AgentSmith.Comments.Reflow.ReflowAndRetagCodeCleanup.SetDefaultSetting(CodeCleanupProfile profile, DefaultProfileType profileType) in E:\Projects\AgentSmith R#2016.1\src\src\AgentSmith\Comments\Reflow\ReflowAndRetagCodeCleanup.cs:line 42
     at JetBrains.ReSharper.Feature.Services.CodeCleanup.CodeCleanupSettingsComponent.GetDefaultProfile(DefaultProfileType profileType)
     at JetBrains.ReSharper.Feature.Services.CodeCleanup.CodeCleanupSettingsComponent.GetProfiles(IContextBoundSettingsStore store)
     at JetBrains.ReSharper.Features.Altering.CodeCleanup2.ViewModels.CleanupToolViewModelFactory.InitializeProfiles(IContextBoundSettingsStore contextBoundSettingsStore)
     at JetBrains.ReSharper.Features.Altering.CodeCleanup2.ViewModels.Options.CodeCleanupOptionsPageViewModel.get_ToolViewModel()
     at JetBrains.PsiFeatures.UIInteractive.Features.Altering.CodeCleanup2.Options.CleanupOptionsPageView.DataContextCoerceValueCallback(DependencyObject dependencyObject, Object baseValue)

**Comment by sheitmann** [comment]
@Rob300
Thanks for reporting. I fixed the bug and uploaded a new update. Should be available soon after it has been approved by Jetbrains.
